version: '3.5'

services:
  contracts-env:
    env_file:
      - .env
    build:
      context: ./
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/app
      - $HOME/.tenderly/config.yaml:/root/.tenderly/config.yaml
