[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', 'solmate/=lib/solmate/src/', 'lens/=contracts/', '@openzeppelin/=node_modules/@openzeppelin/']
fuzz_runs=10000

# See more config options https://github.com/gakonst/foundry/tree/master/config